[variables]
main_domain = "${domain}"
api_key = "${password:64}"

[config]
env = [
  "API_KEY=${api_key}",
  "PROVIDER=openrouter",
  "MENTAT_ALLOW_PUBLIC_BIND=true",
  "MENTAT_GATEWAY_PORT=42617"
]

[[config.domains]]
serviceName = "mentat"
port = 42617
host = "${main_domain}"
